@baseURL = http://localhost:3333

# @name CreateSchedule
POST {{baseURL}}/schedules
Content-Type: application/json

{
  "dataHoraInicio": "2025-06-12T14:00:00.000Z",
  "dataHoraFim": "2025-06-12T15:00:00.000Z",
  "status": "confirmado",
  "userId": "ab0b48f1-6add-405e-8568-0d011b05848e",
  "courtId": "f3fbbaff-98ac-4de3-8a75-4b40a939fe5e"
}

###

# @name GetSchedule
POST {{baseURL}}/schedules/get
Content-Type: application/json

{
  "id": "d461e348-ef5f-40a9-8909-dbf0d92edb88"
}

###

# @name UpdateSchedule
PUT {{baseURL}}/schedules/update
Content-Type: application/json

{
  "id": "d461e348-ef5f-40a9-8909-dbf0d92edb88",
  "dataHoraInicio": "2025-06-12T16:00:00.000Z",
  "dataHoraFim": "2025-06-12T17:00:00.000Z",
  "status": "remarcado"
}

###

# @name DeleteSchedule
POST {{baseURL}}/schedules/delete
Content-Type: application/json

{
  "id": "232c73ef-f159-4677-a401-4ca707bd2cfb"
}
